# Generated by Django 4.0.3 on 2022-04-06 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loaner', models.CharField(max_length=200)),
                ('Date_loaned', models.DateTimeField(auto_now=True)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_games.boardgame')),
            ],
        ),
    ]
