# Generated by Django 4.0.3 on 2022-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0002_rename_year_boardgame_year_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardgame',
            old_name='Game',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='boardgame',
            old_name='Year_published',
            new_name='year_published',
        ),
        migrations.RenameField(
            model_name='gameloan',
            old_name='Date_loaned',
            new_name='date_loaned',
        ),
        migrations.RenameField(
            model_name='gameloan',
            old_name='Game',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='gameloan',
            name='Loaner',
        ),
        migrations.AddField(
            model_name='gameloan',
            name='date_returned',
            field=models.DateField(auto_now=True),
        ),
    ]
