# Generated by Django 4.0.4 on 2022-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0004_remove_gameloan_date_returned_gameloan_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameloan',
            name='returned',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='loaned',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
