# Generated by Django 4.0.4 on 2022-04-12 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_games', '0005_remove_gameloan_returned_boardgame_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameloan',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
