# Generated by Django 4.0.4 on 2022-04-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0006_gameloan_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='loaned',
            field=models.BooleanField(null=True),
        ),
    ]
