# Generated by Django 4.0.3 on 2022-04-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0007_alter_boardgame_loaned'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameloan',
            name='returned',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
