# Generated by Django 4.0.3 on 2022-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_games', '0008_gameloan_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='loaned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameloan',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
